name: Terraform Deployment

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

env:
  AZURE_CLIENT_ID: "85fcd693-7ed7-45d4-b754-6f9d67972229"
  AZURE_TENANT_ID: "7baa4835-0dd6-4321-9180-6a270c0e6f38"
  AZURE_CLIENT_SECRET: "qdS8Q~WJfemcgd3DUY4.NZlxffoD.pnIoG-OsbCc"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0  # Adjust version as needed

    - name: Check if Terraform is initialized
      run: |
        if [ ! -d ".terraform" ]; then
          terraform init -upgrade
        else
          echo "Terraform is already initialized."
        fi

    - name: Azure Login
      run: az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID

    - name: Terraform Plan
      run: terraform plan -out main.tfplan

    - name: Terraform Apply
      run: terraform apply main.tfplan -auto-approve
